// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCGvVMVKQT_mAu63_Tjz1nEfsBzDcw17Uo',
    appId: '1:1071008491671:web:0a3613827c8b80160fa1d2',
    messagingSenderId: '1071008491671',
    projectId: 'ic-task',
    authDomain: 'ic-task.firebaseapp.com',
    storageBucket: 'ic-task.firebasestorage.app',
    measurementId: 'G-PS7VJRXBD5',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBLtWnFX-y2X0VdnyNbdAP1f_gST9p78ck',
    appId: '1:1071008491671:android:d0b47e0f622f65680fa1d2',
    messagingSenderId: '1071008491671',
    projectId: 'ic-task',
    storageBucket: 'ic-task.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBTvIZUne_no3IVE4BVF7Qm8jIOVAr8rB8',
    appId: '1:1071008491671:ios:174d833f3142fdbe0fa1d2',
    messagingSenderId: '1071008491671',
    projectId: 'ic-task',
    storageBucket: 'ic-task.firebasestorage.app',
    iosBundleId: 'com.example.flutterGetxTask',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBTvIZUne_no3IVE4BVF7Qm8jIOVAr8rB8',
    appId: '1:1071008491671:ios:174d833f3142fdbe0fa1d2',
    messagingSenderId: '1071008491671',
    projectId: 'ic-task',
    storageBucket: 'ic-task.firebasestorage.app',
    iosBundleId: 'com.example.flutterGetxTask',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCGvVMVKQT_mAu63_Tjz1nEfsBzDcw17Uo',
    appId: '1:1071008491671:web:ddb5b191ac16e92e0fa1d2',
    messagingSenderId: '1071008491671',
    projectId: 'ic-task',
    authDomain: 'ic-task.firebaseapp.com',
    storageBucket: 'ic-task.firebasestorage.app',
    measurementId: 'G-7G2DPC6WMP',
  );
}
